In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [37]:
state = 'RS'

df_ar = pd.read_csv(f'for_arima_se_1_{state}.csv.gz')

df_ar.head()

         date        pred      lower       upper
0  2025-01-05  101.810220  22.692874  597.424420
1  2025-01-12   96.502561  18.061775  725.814564
2  2025-01-19   92.737987  14.055961  955.162364

In [38]:
df_ar_old = pd.read_csv(f'/Users/eduardoaraujo/Documents/Github/ensemble_curto_prazo/forecast_tables/for_arima_se_1_{state}.csv.gz')

df_ar_old.head()

         date        pred      lower       upper
0  2025-01-05  101.508398  24.092185  541.813336
1  2025-01-12   96.693482  18.947047  673.326956
2  2025-01-19   93.038765  14.644657  891.420566

In [39]:
df_gp = pd.read_csv(f'for_gp_se_1_{state}.csv.gz')

df_gp.head()

         date       pred      lower       upper
0  2025-01-05  54.334230  26.545086  108.493887
1  2025-01-12  49.613219  24.530145   97.968663
2  2025-01-19  43.952630  21.774201   86.631748

In [40]:
df_gp_old = pd.read_csv(f'/Users/eduardoaraujo/Documents/Github/ensemble_curto_prazo/forecast_tables/for_gp_se_1_{state}.csv.gz')

df_gp_old.head()

         date       pred      lower       upper
0  2025-01-05  56.919706  28.678532  110.433762
1  2025-01-12  51.883761  26.260065  100.237126
2  2025-01-19  45.865859  23.105747   88.999666

In [41]:
df_lstm = pd.read_csv(f'for_lstm_se_1_{state}.csv.gz')

df_lstm.head()

         date      lower        pred       upper
0  2025-01-05  85.362272  119.547344  168.509172
1  2025-01-12  71.720925  100.148899  134.426726
2  2025-01-19  58.520924   78.725601  109.299866

In [42]:
df_lstm_old = pd.read_csv(f'/Users/eduardoaraujo/Documents/Github/ensemble_curto_prazo/forecast_tables/for_lstm_1_{state}.csv',
                         index_col = 'Unnamed: 0')

df_lstm_old.head()

         date  lower_2_5    lower_25    forecast    upper_75  upper_97_5
0  2025-01-05  90.305164  124.128986  142.448555  158.625469  208.101898
1  2025-01-12  85.709846  114.736715  127.939499  143.548855  184.914634
2  2025-01-19  82.209999  104.605745  114.824165  129.002846  175.616471