In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('dengue_AC.csv.gz')

df.tail()

           date  SE     casos  diff_casos  casos_mean  casos_std  casos_slope
776  2024-12-08  50  6.112782    0.300680    5.602897   0.375272     0.322220
777  2024-12-15  51  6.118703    0.005920    5.827379   0.347053     0.285900
778  2024-12-22  52  6.441811    0.323108    6.121349   0.222716     0.189504
779  2024-12-29   1  6.684794    0.242984    6.339522   0.239712     0.203914
780  2025-01-05   2  6.715413    0.030619    6.490180   0.239238     0.203311

In [4]:
df = pd.read_csv('dengue_SE.csv.gz')

df.tail()

           date  SE     casos  diff_casos  casos_mean  casos_std  casos_slope
775  2024-12-01  49  3.076980    0.101787    2.996534   0.053825     0.041456
776  2024-12-08  50  3.246003    0.169023    3.075833   0.104979     0.082432
777  2024-12-15  51  2.352922   -0.893081    2.912774   0.337393    -0.169779
778  2024-12-22  52  2.378208    0.025285    2.763528   0.402524    -0.298940
779  2024-12-29   1  2.188580   -0.189628    2.541428   0.413250    -0.314698